### ISSUE TITLE
ライフサイクルコールバック風メソッド

### ISSUE THREAD

**Issue by te-koyama** [te-koyama/arealunch#2]
また、メソッドの責務として
1. Viewの生成
1. 生成したViewを`setContentView`する

を求めているのかと思うのですが、`setContentView`はBase側で呼んだほうが、bindの時点でViewのセットがされているのが確実になるので、
```kotlin
fun getLayoutId(): Int
```
とか
```kotlin
fun onCreateView(): View
```
とかの方が良いかなと思いました。

_Originally posted by @kazkn in https://github.com/te-koyama/arealunch/pull/1#discussion_r231779443

**Comment by te-koyama** [comment]
> メソッドの責務として
> 
> 1. Viewの生成
> 2. 生成したViewをsetContentViewする
> を求めているのかと思うのですが、
ここまでOK

> `setContentView` はBase側で呼んだほうが、bindの時点でViewのセットがされているのが確実になるので、
？？？

**Comment by te-koyama** [comment]
```
override fun onCreate(savedInstanceState: Bundle?) {
//TODO        AndroidInjection.inject(this)
        super.onCreate(savedInstanceState)
        setContentView(getLayoutId())
        basePresenter?.attachView(this as BaseView)
        ButterKnife.bind(this)
    }

    /**
     * レイアウト設定
     */
    abstract fun getLayoutId(): Int
```

/**
     * レイアウト設定
     */
    override fun getLayoutId() = R.layout.activity_sign_in

**Comment by te-koyama** [comment]
こういう事？

**Comment by kazkn** [comment]
@te-koyama これで大丈夫だと思います。

こうする事で、継承クラス側の責務がレイアウトファイルのidを返すだけと単純化されるのと、idが返されてsetContentView()を呼び出される事が確実(継承クラス側にその実装があるばあい、確実に実装されているか基底クラス側では保証できない)となるので、その後の処理でViewが生成されている事を前提とした処理がかけていいかなと思います。

継承クラス側でのViewの指定が単純にレイアウトファイルに限らない(ある画面ではViewインスタンスを直接newするような場合)などは
```
fun onCreateView: View
```
みたいにViewを返すような定義としてもいいかなと思います。

ご納得いただければこちらクローズいただければ。

**Comment by te-koyama** [comment]
@kazkn
