### ISSUE TITLE
RecyclerViewのAdapterとViewPagerのAdapterは別物なので、分類したほうがいい

### ISSUE THREAD

**Issue by te-koyama** [te-koyama/arealunch#6]
_Originally posted by @kazkn in https://github.com/te-koyama/arealunch/pull/5_

**Comment by te-koyama** [comment]
TabsAdapter.ktを指してますが、具体的にどの部分を言われてるのか不明で分からない。
ListAdapterの事？

**Comment by kazkn** [comment]
@te-koyama 最後がAdapterだからといって同じadapterパッケージに入れるのはどうなのだろうという事です。

**Comment by te-koyama** [comment]
@kazkn あ、なるほど了解しました。
